### ISSUE TITLE
GCC 15 compile issue with included scintilla

### ISSUE THREAD

**Issue by h3o66** [dail8859/NotepadNext#752]
With the 2 latest releases , 0.10 and 0.11 the compile fails with GCC 15 on Fedora 42 .

Build error:
```
In file included from ../../src/scintilla/qt/ScintillaEdit/ScintillaDocument.cpp:13:
../../src/scintilla/include/ScintillaTypes.h:699:18: error: ‘intptr_t’ does not name a type
  699 | using Position = intptr_t;
      |                  ^~~~~~~~
../../src/scintilla/include/ScintillaTypes.h:1:1: note: ‘intptr_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
  +++ |+#include <cstdint>
    1 | // Scintilla source code edit control
../../src/scintilla/include/ScintillaTypes.h:700:14: error: ‘intptr_t’ does not name a type
  700 | using Line = intptr_t;
      |              ^~~~~~~~
../../src/scintilla/include/ScintillaTypes.h:700:14: note: ‘intptr_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
../../src/scintilla/include/ScintillaTypes.h:703:16: error: ‘uintptr_t’ does not name a type
  703 | using uptr_t = uintptr_t;
      |                ^~~~~~~~~
../../src/scintilla/include/ScintillaTypes.h:703:16: note: ‘uintptr_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
../../src/scintilla/include/ScintillaTypes.h:704:16: error: ‘intptr_t’ does not name a type
  704 | using sptr_t = intptr_t;
      |                ^~~~~~~~
../../src/scintilla/include/ScintillaTypes.h:704:16: note: ‘intptr_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
../../src/scintilla/include/ScintillaTypes.h:708:11: error: ‘Position’ does not name a type
  708 | constexpr Position InvalidPosition = -1;
      |           ^~~~~~~~
In file included from ../../src/scintilla/qt/ScintillaEdit/ScintillaDocument.cpp:15:
../../src/scintilla/include/ScintillaStructures.h:23:9: error: ‘Position’ does not name a type; did you mean ‘PositionCR’?
   23 |         Position cpMin;
      |         ^~~~~~~~
      |         PositionCR
../../src/scintilla/include/ScintillaStructures.h:24:9: error: ‘Position’ does not name a type; did you mean ‘PositionCR’?
   24 |         Position cpMax;
      |         ^~~~~~~~
      |         PositionCR
../../src/scintilla/include/ScintillaStructures.h:81:9: error: ‘uptr_t’ does not name a type
   81 |         uptr_t idFrom;
      |         ^~~~~~
../../src/scintilla/include/ScintillaStructures.h:89:9: error: ‘Position’ does not name a type; did you mean ‘PositionCR’?
   89 |         Position position;
      |         ^~~~~~~~
      |         PositionCR
../../src/scintilla/include/ScintillaStructures.h:107:9: error: ‘Position’ does not name a type; did you mean ‘PositionCR’?
  107 |         Position length;                /* SCN_MODIFIED */
      |         ^~~~~~~~
      |         PositionCR
../../src/scintilla/include/ScintillaStructures.h:108:9: error: ‘Position’ does not name a type; did you mean ‘PositionCR’?
  108 |         Position linesAdded;    /* SCN_MODIFIED */
      |         ^~~~~~~~
      |         PositionCR
../../src/scintilla/include/ScintillaStructures.h:110:9: error: ‘uptr_t’ does not name a type
  110 |         uptr_t wParam;  /* SCN_MACRORECORD */
      |         ^~~~~~
../../src/scintilla/include/ScintillaStructures.h:111:9: error: ‘sptr_t’ does not name a type
  111 |         sptr_t lParam;  /* SCN_MACRORECORD */
      |         ^~~~~~
../../src/scintilla/include/ScintillaStructures.h:112:9: error: ‘Position’ does not name a type; did you mean ‘PositionCR’?
  112 |         Position line;          /* SCN_MODIFIED */
      |         ^~~~~~~~
      |         PositionCR
../../src/scintilla/include/ScintillaStructures.h:120:9: error: ‘Position’ does not name a type; did you mean ‘PositionCR’?
  120 |         Position annotationLinesAdded;  /* SCN_MODIFIED with SC_MOD_CHANGEANNOTATION */
      |         ^~~~~~~~
      |         PositionCR
In file included from ../../src/scintilla/qt/ScintillaEdit/ScintillaDocument.cpp:38:
../../src/scintilla/src/ViewStyle.h:42:49: error: ‘uptr_t’ is not a member of ‘Scintilla’; did you mean ‘uptr_t’?
   42 | inline ColourOptional OptionalColour(Scintilla::uptr_t wParam, Scintilla::sptr_t lParam) noexcept {
      |                                                 ^~~~~~
In file included from ../../src/scintilla/qt/ScintillaEdit/ScintillaDocument.cpp:24:
../../src/scintilla/include/Scintilla.h:32:19: note: ‘uptr_t’ declared here
   32 | typedef uintptr_t uptr_t;
      |                   ^~~~~~
../../src/scintilla/src/ViewStyle.h:42:75: error: ‘sptr_t’ is not a member of ‘Scintilla’; did you mean ‘sptr_t’?
   42 | inline ColourOptional OptionalColour(Scintilla::uptr_t wParam, Scintilla::sptr_t lParam) noexcept {
      |                                                                           ^~~~~~
../../src/scintilla/include/Scintilla.h:34:18: note: ‘sptr_t’ declared here
   34 | typedef intptr_t sptr_t;
      |                  ^~~~~~
../../src/scintilla/src/ViewStyle.h:42:90: error: expected ‘,’ or ‘;’ before ‘noexcept’
   42 | inline ColourOptional OptionalColour(Scintilla::uptr_t wParam, Scintilla::sptr_t lParam) noexcept {
      |                                                                                          ^~~~~~~~
../../src/scintilla/src/ViewStyle.h:229:67: error: ‘Scintilla::uptr_t’ has not been declared
  229 |         bool SetElementColourOptional(Scintilla::Element element, Scintilla::uptr_t wParam, Scintilla::sptr_t lParam);
      |                                                                   ^~~~~~~~~
../../src/scintilla/src/ViewStyle.h:229:93: error: ‘Scintilla::sptr_t’ has not been declared
  229 |         bool SetElementColourOptional(Scintilla::Element element, Scintilla::uptr_t wParam, Scintilla::sptr_t lParam);
      |                                                                                             ^~~~~~~~~

```

For the include of `<cstdint>`
First i checked their bugtracker, but it seems that this would be related:
https://sourceforge.net/p/scintilla/bugs/2458/

but that was already coded with this commit:
https://sourceforge.net/p/scintilla/code/ci/c7ffad21b23dfad4e8e9f36bb587acc2f6e84fee/

From my side i could only fix this with this patch:
```
diff --git a/src/scintilla/qt/ScintillaEdit/ScintillaDocument.cpp b/src/scintilla/qt/ScintillaEdit/ScintillaDocument.cpp
index fc5ef2e..71bbaf0 100644
--- a/src/scintilla/qt/ScintillaEdit/ScintillaDocument.cpp
+++ b/src/scintilla/qt/ScintillaEdit/ScintillaDocument.cpp
@@ -9,6 +9,7 @@
 #include <set>
 #include <optional>
 #include <memory>
+#include <cstdint>
 
 #include "ScintillaTypes.h"
 #include "ScintillaMessages.h"

```

I am currently not sure if that is 100% a issue with upstream or related how the dependency is built with this project.

**Comment by dail8859** [comment]
Thanks for opening this issue.

It seems that the Scintilla project on SourceForge would be the best place to get this fixed so I would definitely contact that project.

Until then if you create a PR I'd be glad to accept it in this project until it can get fixed upstream permanently.

**Comment by dail8859** [comment]
What commit was it fixed in Scintilla? Is v5.5.6 working or is it in the master branch?

**Comment by SigHunter** [comment]
is this fixed for you in 0.12?

this still happens to me when building NotepadNext 0.12 from source, this time the issue is with ViewStyle.h

```
In file included from ../src/scintilla/qt/ScintillaEdit/ScintillaDocument.cpp:38:
../src/scintilla/src/ViewStyle.h:42:49: error: ‘uptr_t’ is not a member of ‘Scintilla’; did you mean ‘uptr_t’?
   42 | inline ColourOptional OptionalColour(Scintilla::uptr_t wParam, Scintilla::sptr_t lParam) noexcept {
      |                                                 ^~~~~~
In file included from ../src/scintilla/qt/ScintillaEdit/ScintillaDocument.cpp:24:
../src/scintilla/include/Scintilla.h:32:19: note: ‘uptr_t’ declared here
   32 | typedef uintptr_t uptr_t;
      |                   ^~~~~~
../src/scintilla/src/ViewStyle.h:42:75: error: ‘sptr_t’ is not a member of ‘Scintilla’; did you mean ‘sptr_t’?
   42 | inline ColourOptional OptionalColour(Scintilla::uptr_t wParam, Scintilla::sptr_t lParam) noexcept {
      |                                                                           ^~~~~~
../src/scintilla/include/Scintilla.h:34:18: note: ‘sptr_t’ declared here
   34 | typedef intptr_t sptr_t;
      |                  ^~~~~~
../src/scintilla/src/ViewStyle.h:42:90: error: expected ‘,’ or ‘;’ before ‘noexcept’
   42 | inline ColourOptional OptionalColour(Scintilla::uptr_t wParam, Scintilla::sptr_t lParam) noexcept {
      |                                                                                          ^~~~~~~~
x86_64-pc-linux-gnu-g++ -c -march=native -O2 -pipe -flto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -std=gnu++1z -Wall -Wextra -mno-direct-extern-access -D_REENTRANT -DAPP_VERSION="\"0.12\"" -DAPP_COPYRIGHT="\"Copyright 2019-2025 Justin Dailey\"" -DAPP_DISTRIBUTION="\"\"" -DSCI_OWNREGEX -DADS_STATIC -DQAPPLICATION_CLASS=QApplication -DSCINTILLA_QT=1 -DMAKING_LIBRARY=1 -DSCI_LEXER=1 -D_CRT_SECURE_NO_DEPRECATE=1 -DEXPORT_IMPORT_API= -DNDEBUG=1 -DLUA_PATH_DEFAULT=\"\" -DLUA_CPATH_DEFAULT=\"\" -DLUA_VERSION_NUM=503 -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE5COMPAT_LIB -DQT_CORE_LIB -I../src/NotepadNext -I. -I../src/singleapplication -I../src/scintilla/qt/ScintillaEditBase -I../src/scintilla/qt/ScintillaEdit -I../src/scintilla/include -I../src/scintilla/src -I../src/lexilla/access -I../src/lexilla/lexlib -I../src/lexilla/include -I../src/uchardet/src -I../src/lua/src -I../src/ads/src -I../src/editorconfig-core-qt -I../src/NotepadNext/decorators -I../src/NotepadNext/dialogs -I../src/NotepadNext/docks -I../src/NotepadNext/widgets -I../src -I../src/lexilla/include -I/usr/include/qt6 -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui/6.9.1 -I/usr/include/qt6/QtGui/6.9.1/QtGui -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore5Compat -I/usr/include/qt6/QtCore/6.9.1 -I/usr/include/qt6/QtCore/6.9.1/QtCore -I/usr/include/qt6/QtCore -Ibuild/moc -Ibuild/ui -I/usr/lib64/qt6/mkspecs/linux-g++ -o build/obj/Geometry.o ../src/scintilla/src/Geometry.cxx
../src/scintilla/src/ViewStyle.h:229:67: error: ‘Scintilla::uptr_t’ has not been declared
  229 |         bool SetElementColourOptional(Scintilla::Element element, Scintilla::uptr_t wParam, Scintilla::sptr_t lParam);
      |                                                                   ^~~~~~~~~
../src/scintilla/src/ViewStyle.h:229:93: error: ‘Scintilla::sptr_t’ has not been declared
  229 |         bool SetElementColourOptional(Scintilla::Element element, Scintilla::uptr_t wParam, Scintilla::sptr_t lParam);
      |                                                                                             ^~~~~~~~~

```

GCC 15.1, Qt6.9.1

[build.log](https://github.com/user-attachments/files/20934559/build.log)

**Comment by dail8859** [comment]
At least from my side, v0.12 uses the latest Scintilla version so if there's still issues building with gcc you might need to report those to the Scintilla project. But maybe someone else had some better luck :)

**Comment by SigHunter** [comment]
I managed to work around it by using 
`sed -i '1i #include <cstdint>' "${S}"/src/scintilla/include/ScintillaTypes.h `
which is basically 
https://github.com/dail8859/NotepadNext/commit/0aebd26b7ccaf5508c10f353c8776f7fa09db5c0 
from https://github.com/dail8859/NotepadNext/pull/670
but it probably got lost when pulling new upstream scintilla

**Comment by dail8859** [comment]
#670 was a temporary fix until the upstream library fixed it permanently. I thought it was fixed upstream. So updating the library this time seems to have broken it again. Your best opinion is to get Scintilla to fix it.
